config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'boards', to: 'boards#index'
  get 'boards', to: 'boards#show'
  get 'boards', to: 'boards#calendar'
  get 'boards/show', to: 'boards#show'
  get 'events', to: 'events#index'
  get 'seasons', to: 'seasons#index'

  resources :articles  

  get 'voices', to: 'voices#index'
  get 'recruits', to: 'recruits#index'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :picture, PictureUploader

  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :content, presence: true

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token    

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
						  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_target_article, only: %i[show edit update destroy]

  def index
    @articles = Article.page(params[:page]).per(5).search(params[:search])
  end
    
  def new
    @article = Article.new
  end

  def create
    article = Article.new(article_params)
    if article.save
      redirect_to article
    else
      redirect_to new_article_path, flash: {
        error_messages: article.errors.full_messages
      }
    end
  end

  def show
  end

  def edit
  end

  def update
    @article.update(article_params)

    redirect_to @article
  end

  def destroy
    @article.delete

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :picture, :content)
  end

  def set_target_article
    @article = Article.find(params[:id])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
  end

  def show
  end

  def calendar
    gon.google_calendar_API_key = ENV['GOOGLE_CALENDAR_API_KEY']
    gon.calendar_id_1 = ENV['CALENDAR_ID_1']
    gon.calendar_id_2 = ENV['CALENDAR_ID_2']
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  def index
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to "/boards" if current_user
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
       log_in(user)
       params[:session][:remember_me] == '1' ? remember(user) : forget(user)
       redirect_to "/boards"
    else
      flash.now[:danger] = '有効なメールアドレス、またはパスワードではありません。'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to "/login"
  end
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find.by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/articles/edit.html.erb
<% content_for(:html_title) { 'CTD CAFE | 記事編集' } %>
<%= stylesheet_link_tag "new" %>

<body>
  <div id="home">
        <header class="page-header wrapper">
            <h1 data-aos="fade-right" data-aos-delay="300" data-aos-duration="3000">
                <a href="/boards">
                    <img class="logo" src="/assets/cafe_logo.png" alt="ロゴ">
                    <span class="logo_title">CTD CAFE</span>
                </a>
            </h1>
            <nav data-aos="fade-left" data-aos-delay="300" data-aos-duration="3000">
                <ul class="main-nav">
                    <li><a class="button" href="/boards">Home</a></li>
                    <li><a class="button" href="/articles">Articles</a></li>
                    <% if logged_in? %>
                    <li>
                      <%= link_to "Out", '/login', method: :delete, class: 'button' %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </header>

        <div class="wrapper">
          <h2>記事編集フォーム</h2>
          <%= form_for @article do |f| %>
            <div class="form-group">
              <%= f.label 'タイトル' %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group image">
              <%= f.label '画像' %>
              <%= f.file_field :image %>
            </div>
            <div class="form-group">
              <%= f.label '本文' %>
              <%= f.text_area :content, class: 'form-control', rows: 10 %>
            </div>
            <%= f.submit '投稿する', class: 'submit-btn' %>
          <% end %>
        </div>

        <footer>
          <div class="wrapper">
            <p><small>&copy; 2020 CTD CAFE</small></p>
          </div>
        </footer>
  </div>
</body>

app/views/articles/index.html.erb
<% content_for(:html_title) { 'CTD CAFE | 期間限定/新メニュー'} %>
<%= stylesheet_link_tag "articles" %>
<link href="/assets/aos.css" rel="stylesheet">

<body>
    <div id="home">
        <%= render "boards/header" %>
    </div>

    <div id="menu">
        <div class="wrapper">
            <h2 class="page-title" data-aos="fade-up" data-aos-delay="300" data-aos-duration="2000" data-aos-anchor-placement="center-bottom">期間限定/新メニュー</h2>
        </div>
    </div>

    <main>
        <div class="menu-contents wrapper">
            <ul class="list container">
                <% @articles.each do |article| %>
                    <li class="list-article">
                        <%= link_to article do %>
                            <div class="list-image">
                                <% if article.picture? %>
                                    <%= image_tag article.picture.to_s, class: 'img-thumb' %>
                                <% end %>
                            </div>
                            <div class="list-item">
                                <h3><%= article.title %></h3>
                                <span class="list-tag"><%= article.created_at.to_s(:datetime_jp) %></span>
                                <p><%= article.content %></p>
                            </div>
                        <% end %>
                    </li>
                    <% if logged_in? %>
                        <%= link_to article, method: :delete do %>
                        　<span class="fa fa-trash"></span>
                        <% end %>
                    <% end %>
                <% end %>
            </ul>

            <aside>
                <h3 class="sub-title">キーワードで探す</h3>
                <div class="search_container">
                    <%= form_tag(articles_path, method: :get) do %>
                    <%= text_field_tag :search %>
                    <%= submit_tag "検索", :title => nil, class: 'input-submit' %>
                    <% end%>
                </div>

                <h3 class="sub-title">カテゴリー</h3>
                <ul class="sub-menu">
                    <li class="commitment"><a href="/boards/show">こだわり</a></li>
                    <li class="menu"><a href="/articles">期間限定/新メニュー</a></li>
                    <li class="event"><a href="/events">イベント</a></li>
                    <li class="voice"><a href="/voices">よくあるご質問</a></li>
                    <li class="recruit"><a href="/recruits">採用情報</a></li>
                </ul>

                <h3 class="sub-title">店長コメント</h3>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi aliquid fugit nihil ab? Dolor repudiandae nihil amet veniam dolorum iste minus ea esse recusandae sapiente nam, cumque eos voluptas minima.
                </p>

                <% if logged_in? %>
                    <a>
                      <%= link_to "記事作成", '/articles/new', class: 'btn-flat-border' %>
                    </a>
                <% end %>
            </aside>
        </div>
    </main>

    <%= paginate @articles %>

    <%= render "boards/footer" %>

    <script src="/assets/aos.js"></script>
    <script src="/assets/topbutton.js"></script>
</body>

app/views/articles/new.html.erb
<% content_for(:html_title) { 'CTD CAFE | 記事新規投稿' } %>
<%= stylesheet_link_tag "new" %>

<body>
  <div id="home">
        <header class="page-header wrapper">
            <h1 data-aos="fade-right" data-aos-delay="300" data-aos-duration="3000">
                <a href="/boards">
                    <img class="logo" src="/assets/cafe_logo.png" alt="ロゴ">
                    <span class="logo_title">CTD CAFE</span>
                </a>
            </h1>
            <nav data-aos="fade-left" data-aos-delay="300" data-aos-duration="3000">
                <ul class="main-nav">
                    <li><a class="button" href="/boards">Home</a></li>
                    <li><a class="button" href="/articles">Articles</a></li>
                    <% if logged_in? %>
                    <li>
                      <%= link_to "Out", '/login', method: :delete, class: 'button' %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </header>

        <% if flash[:error_messages] %>
          <div class="alert wrapper">
            <ul>
              <% flash[:error_messages].each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="wrapper">
          <h2>新規記事作成フォーム</h2>
          <%= form_for @article do |f| %>
            <div class="form-group">
              <%= f.label 'タイトル' %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group image">
              <%= f.label '画像' %><br>
              <%= f.file_field :picture %>
            </div>
            <div class="form-group">
              <%= f.label '本文' %>
              <%= f.text_area :content, class: 'form-control', rows: 10 %>
            </div>
            <%= f.submit '投稿する', class: 'submit-btn' %>
          <% end %>
        </div>

        <footer>
          <div class="wrapper">
            <p><small>&copy; 2020 CTD CAFE</small></p>
          </div>
        </footer>
  </div>
</body>

app/views/articles/show.html.erb
<% content_for(:html_title) { 'CTD CAFE | 期間限定/新メニュー'} %>
<%= stylesheet_link_tag "show", :media => "all" %>
<link href="/assets/aos.css" rel="stylesheet">


    <div id="home">
        <header class="page-header wrapper">
            <h1 data-aos="fade-right" data-aos-delay="300" data-aos-duration="3000">
                <a href="/boards">
                    <img class="logo" src="/assets/cafe_logo.png" alt="ロゴ">
                    <span class="logo_title">CTD CAFE</span>
                </a>
            </h1>
            <nav data-aos="fade-left" data-aos-delay="300" data-aos-duration="3000">
                <ul class="main-nav">
                    <li><a class="button" href="/boards">Home</a></li>
                    <li><a class="button" href="/articles">Article</a></li>
                    <% if logged_in? %>
                    <li>
                        <%= link_to 'Edit', edit_article_path(@article), class: 'button' %>
                    </li>
                    <li>
                      <%= link_to "Out", '/login', method: :delete, class: 'button' %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </header>
    </div>

    <div class="introduction-contents wrapper">
        <article>
            <header class="post-info" data-aos="fade-zoom-in" data-aos-easing="ease-in-out-sine" data-aos-delay="700" data-aos-offset="0">
                <h2 class="post-title"><%= @article.title %></h2>
            </header>
            <% if @article.picture? %>
                <%= image_tag @article.picture.to_s %>
            <% end %>
            <p>
                <%= simple_format(@article.content) %>
            </p>
        </article>

        <aside data-aos="fade-zoom-in" data-aos-easing="ease-in-out-sine" data-aos-delay="700" data-aos-offset="0">
            <h3 class="sub-title">カテゴリー</h3>
            <ul class="sub-menu">
                <li class="commitment"><a href="/boards/show">こだわり</a></li>
                <li class="menu"><a href="/articles">期間限定/新メニュー</a></li>
                <li class="event"><a href="/events">イベント</a></li>
                <li class="voice"><a href="/voices">よくあるご質問</a></li>
                <li class="recruit"><a href="/recruits">採用情報</a></li>
            </ul>

            <h3 class="sub-title">店長コメント</h3>
            <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi aliquid fugit nihil ab? Dolor repudiandae nihil amet veniam dolorum iste minus ea esse recusandae sapiente nam, cumque eos voluptas minima.
            </p>

            <% if logged_in? %>
                <a>
                  <%= link_to "記事作成", '/articles/new', class: 'btn-flat-border' %>
                </a>
            <% end %>
        </aside>
    </div>

    <%= render "boards/footer" %>

    <script src="/assets/aos.js"></script>
    <script src="/assets/topbutton.js"></script>

app/views/boards/_aside.html.erb
<aside>
    <h3 class="sub-title">カテゴリー</h3>
        <ul class="sub-menu">
            <li class="commitment"><a href="/boards/show">こだわり</a></li>
            <li class="menu"><a href="/articles">期間限定/新メニュー</a></li>
            <li class="event"><a href="/events">イベント</a></li>
            <li class="voice"><a href="/voices">よくあるご質問</a></li>
            <li class="recruit"><a href="/recruits">採用情報</a></li>
        </ul>

        <h3 class="sub-title">店長コメント</h3>
            <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi aliquid fugit nihil ab? Dolor repudiandae nihil amet veniam dolorum iste minus ea esse recusandae sapiente nam, cumque eos voluptas minima.
            </p>

</aside>

app/views/boards/_footer.html.erb
<div id="pagetop" class="pagetop">
    <a href="#" class="pagetopB">TOP</a>
</div>

<footer>
    <ul class="footer-nav">
        <li class="commitment"><a href="/boards/show" class="nav-button">こだわり</a></li>
        <li class="menu"><a href="/articles" class="nav-button">期間限定/新メニュー</a></li>
        <li class="event"><a href="/events" class="nav-button">イベント</a></li>
        <li class="voice"><a href="/voices" class="nav-button">よくあるご質問</a></li>
        <li class="recruit"><a href="/recruits" class="nav-button">採用情報</a></li>
    </ul>
    <div class="wrapper">
        <p><small>&copy; 2020 CTD CAFE</small></p>
    </div>
</footer>

app/views/boards/_header.html.erb
<header id="Home" class="page-header wrapper">
    <h1 data-aos="fade-right" data-aos-delay="300" data-aos-duration="3000">
         <a href="/boards">
            <img class="logo" src="/assets/cafe_logo.png" alt="ロゴ">
                <span class="logo_title">CTD CAFE</span>
            </a>
    </h1>
    <nav data-aos="fade-left" data-aos-delay="300" data-aos-duration="3000">
        <ul class="main-nav">
            <li><a class="button home-btn" href="/boards">Home</a></li>
            <li><%= link_to 'NEWS', boards_path(anchor: 'News'), class: 'button news-btn' %></li>
            <li><%= link_to 'MENU', boards_path(anchor: 'Menu'), class: 'button menu-btn' %></li>
            <li><%= link_to 'CONTACT', boards_path(anchor: 'Contact'), class: 'button contact-btn' %></li>
            <% if logged_in? %>
                <li>
                    <%= link_to "Out", '/login', method: :delete, class: 'button' %>
                </li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/boards/index.html.erb
<%= stylesheet_link_tag 'style', :media => "all" %>
<link href="/assets/aos.css" rel="stylesheet">

<section id="home" class="big-bg">
    <%= render "header" %>

    <div class="home-content wrapper" data-aos="fade-up" data-aos-delay="300" data-aos-duration="3000">
        <h2 class="page-title">We Provide The Peaceful Space</h2>
        <p class="subtitle">ゆったりとした空間で最高のコーヒーを<span class="br">お楽しみください</span></p>
    </div><!--  /.home-content -->
</section><!-- #home -->

    <section class="shopify-section">
        <div class="shopify-item">
            <img src="/assets/roasting.jpg" style="max-width: 70px;">
            <p>
                <strong>店舗焙煎・ドリップ</strong>
                <br>
                毎日新鮮なコーヒー豆を焙煎＆ドリップ
            </p>
        </div>
        <div class="shopify-item">
            <img src="/assets/star.jpg" style="max-width: 70px;">
            <p>
                <strong>ハイクオリティ</strong>
                <br>
                プロのバリスタ率いるグループ
            </p>
        </div>
        <div class="shopify-item">
            <img src="/assets/meating.jpg" style="max-width: 70px;">
            <p>
                <strong>直接取引</strong>
                <br>
                現地でコーヒ豆の選定
            </p>
        </div>
    </section>

    <section id="news" class="big-bg">
        <div id="News" class="wrapper">
            <h2 class="page-title" data-aos="fade-up" data-aos-delay="300" data-aos-duration="2000" data-aos-anchor-placement="center-bottom">News</h2>
        </div><!-- .wrapper -->
    </section><!-- #news -->

    <div class="news-contents wrapper">
        <article>
            <header class="post-info">
                <h2 class="post-title">CTD CAFEとは？</h2>
            </header>
            <img src="/assets/coffee-shop.jpg" alt="ショップ内">
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit minima voluptate, esse quo corporis labore eos a laudantium vitae! Nesciunt, veritatis. Voluptatum corrupti nisi distinctio obcaecati eveniet. Consequuntur, autem amet.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad deleniti eum ut facilis magnam aperiam esse accusantium ratione, enim iure, voluptas totam hic nam recusandae corrupti doloremque cupiditate! Illum, commodi?
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus, explicabo soluta voluptate omnis nulla ratione illo, nisi quidem ipsum sed voluptates modi atque, necessitatibus officiis error dolorum? Harum, autem nostrum.
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto doloribus explicabo sapiente labore fuga at in est, quidem alias voluptatum quos quis, magni doloremque expedita numquam repellendus ea ad optio!
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit minima voluptate, esse quo corporis labore eos a laudantium vitae! Nesciunt, veritatis. Voluptatum corrupti nisi distinctio obcaecati eveniet. Consequuntur, autem amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad deleniti eum ut facilis magnam aperiam esse accusantium ratione, enim iure, voluptas totam hic nam recusandae corrupti doloremque cupiditate! Illum, commodi? Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit minima voluptate, esse quo corporis labore eos a laudantium vitae! Nesciunt, veritatis. Voluptatum corrupti nisi distinctio obcaecati eveniet. Consequuntur, autem amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad deleniti eum ut facilis magnam aperiam esse accusantium ratione, enim iure, voluptas totam hic nam recusandae corrupti doloremque cupiditate! Illum, commodi? Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            </p>
        </article>

        <%= render "aside" %>

        <div class="ad">
            <a href="/seasons">
                <img src="/assets/banner.jpg" alt="旬のメニューはこちら">
            </a>
        </div>
    </div><!-- .news-contents -->

    <section id="menu" class="big-bg">
        <div id="Menu" class="menu-content wrapper" data-aos="fade-up" data-aos-delay="300" data-aos-duration="2000" data-aos-anchor-placement="center-bottom">
            <h2 class="page-title">Menu</h2>
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, odit eum amet reprehenderit, commodi alias vel molestiae dolorem itaque aut vitae non, dolores cumque necessitatibus nostrum totam in accusamus expedita.
            </p>
        </div><!-- .menu-content -->
    </section><!-- #menu -->

    <div class="wrapper grid">
        <div class="item">
            <img src="/assets/home-bg.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/coffee2.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/matcha-green-tea.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/sandwich.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/spaghetti.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/gratin.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/ice.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/pudding.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
        <div class="item">
            <img src="/assets/green-tea-cake.jpg" alt="">
            <p>名前が入ります<span>¥700</span></p>
        </div>
    </div>

    <section id="contact" class="big-bg">
        <div id="Contact" class="wrapper">
            <h2 class="page-title" data-aos="fade-right" data-aos-delay="300" data-aos-duration="2000" data-aos-anchor-placement="center-bottom">Contact</h2>
            <form action="#">
                <div>
                    <label for="name">お名前</label>
                    <input type="text" id="name" name="your-name">
                </div>
                <div>
                    <label for="email">メールアドレス</label>
                    <input type="email" id="email" name="your-email">
                </div>
                <div>
                    <label for="message">メッセージ</label>
                    <textarea name="your-message" id="message"></textarea>
                </div>
                <input type="submit" class="button-submit" value="送信">
            </form>
        </div><!-- .wrapper -->
    
    </section><!-- #contact -->
    
    <section id="location">
        <div id="access">
            <h2 class="page-title" data-aos="fade-up" data-aos-delay="300" data-aos-duration="2000" data-aos-anchor-placement="center-bottom">Access</h2>
        </div>
        <div class="wrapper">
            <div class="location-info">
                <h3 class="sub-title">カフェ 南駅前店</h3>
                <p>
                    住所：東京都〇〇区<br>
                    〇〇〇〇〇〇 000-22-3<br>
                    〇〇〇〇<br>
                    電話番号：00-1111-2222<br>
                    営業時間：10:00〜20:00<br>
                    休日：木曜日
                </p>
                <ul class="sns-links">
                    <li><a href="https://twitter.com/share?url=https://safe-anchorage-93849.herokuapp.com/boards"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://www.instagram.com/"><i class="fab fa-facebook"></i></a></li>
                </ul>
            </div><!--/.location-info-->
            <div class="location-map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.828030380883!2d139.76493611533982!3d35.681236180194226!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188bfbd89f700b%3A0x277c49ba34ed38!2z5p2x5Lqs6aeF!5e0!3m2!1sja!2sjp!4v1609330868127!5m2!1sja!2sjp" width="800" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div><!--/.location-map-->
        </div><!--/.wrapper-->
    </section><!--/#location-->

    <section class="calendar-wrapper effect-fade-up">
        <div id="calendar">
            <div class="tabs"></div>
            <div class="tabs"></div>
            <div class="calendar-text">* <span class="brown"></span>木曜日はお休みです。</div>
        </div>
    </section>

    <%= render "footer" %>

    <script src="/assets/aos.js"></script>
    <script src="/assets/topbutton.js"></script>
    <script src="/assets/calendar.js"></script>
    <script src="/assets/gcal.js"></script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:html_title) ? yield(:html_title) : "CTD CAFE" %></title>
    <meta name="description" content="オリジナルブレンドコーヒーと体に優しいヘルシーな料理を提供するカフェ">
    <meta name="keyword" content="コーヒー,ヘルシー,カフェ,料理,オリジナル">
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />

    <%= include_gon %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>

    <meta property="og:url" content="https://safe-anchorage-93849.herokuapp.com/boards">
    <meta property="og:type" content="website">
    <meta property="og:title" content="ページタイトルが入ります">
    <meta property="og:description" content="オリジナルブレンドコーヒーと体に優しいヘルシーな料理を提供するカフェです。">
    <meta property="og:name" content="CTD CAFE">
    <meta property="og:image" content="https://cdn.pixabay.com/photo/2015/10/12/14/54/coffee-983955_1280.jpg">
  </head>

  <body>
    <%= yield %>
  </body>
</html>